import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../shared/models/appointment_model.dart';
import '../../../auth/presentation/providers/auth_provider.dart';

final bookingProvider = StateNotifierProvider<BookingNotifier, AsyncValue<void>>((ref) {
  return BookingNotifier(ref);
});

class BookingNotifier extends StateNotifier<AsyncValue<void>> {
  final Ref _ref;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  BookingNotifier(this._ref) : super(const AsyncValue.data(null));

  Future<void> bookAppointment({
    required String doctorId,
    required String doctorName,
    required String specialty,
    required DateTime dateTime,
    String notes = '',
  }) async {
    state = const AsyncValue.loading();
    try {
      final currentUser = _ref.read(authStateProvider).value;
      if (currentUser == null) throw Exception('User not logged in');

      final appointment = AppointmentModel(
        id: '', // Will be generated by Firestore
        patientId: currentUser.uid,
        doctorId: doctorId,
        doctorName: doctorName,
        specialty: specialty,
        dateTime: dateTime,
        notes: notes,
      );

      await _firestore.collection('appointments').add(appointment.toMap());
      state = const AsyncValue.data(null);
    } catch (e, st) {
      print('Error booking appointment: \$e');
      state = AsyncValue.error(e, st);
    }
  }
}
